x <- c(44, NA, 5, NA)
x*3
y <- rnorm(1000)
#this allows you to make a vector with 1000 NA values
z <- rep(NA, 1000)
#this allows you to draw 100 random samples using numbers from y and z vectors
my_data <- sample(c(y,z), 100)
my_na <- is.na(my_data)
my_na
my_data == NA

sum(my_na)
my_data
#There is a type of of NA which is NaN (Not a Number) generated by dividing over 0 for example or sqrt(-1)
nxt()
0/0
#in R Inf stands for infinity
Inf-Inf

